Revert "fix: don't assign public IPs to demo services (#43)" (#44)
Reverting due to issues connecting to secrets manager:

```
ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret arn:aws:secretsmanager:us-east-2:...:secret:ecs-ci/CPTLSCert/962_1-TxmoDc from secrets manager: RequestCanceled: request context canceled caused by: context deadline exceeded. Please check your task network configuration.
```

This reverts commit dc956f1d053b4b49c4cc8b59bfd51259e1df39ab.